-- lua/minecraft_registry_source.lua
-- Custom blink.cmp completion source for ProbeJS-generated Minecraft registry IDs.
-- Provides fuzzy-filtered completions (e.g. 'minecraft:diamond_sword') inside
-- string literals in TypeScript/JavaScript files, reading from
-- kubejs/probe/registry_objects.json generated by /probejs dump in-game.

local source = {}

-- Per-path cache so reopening Neovim in a different project re-parses.
local _cache = {} -- [path] -> blink CompletionItem[]

local function registry_path()
  return vim.fn.getcwd() .. "/kubejs/probe/registry_objects.json"
end

-- Parse registry_objects.json and build a flat list of CompletionItems.
-- Format: { "registry_name": ["id1", "id2", ...], ... }
local function parse(path)
  if _cache[path] then return _cache[path] end

  local f = io.open(path, "r")
  if not f then return {} end
  local raw = f:read("*a")
  f:close()

  local ok, data = pcall(vim.json.decode, raw)
  if not ok or type(data) ~= "table" then return {} end

  local Value = require("blink.cmp.types").CompletionItemKind.Value
  local Plain = vim.lsp.protocol.InsertTextFormat.PlainText

  local items = {}
  local seen = {} -- deduplicate: keep first occurrence per unique id

  for registry, ids in pairs(data) do
    if type(ids) == "table" then
      for _, id in ipairs(ids) do
        if type(id) == "string" and not seen[id] then
          seen[id] = true
          items[#items + 1] = {
            label = id,
            kind = Value,
            insertText = id,
            insertTextFormat = Plain,
            labelDetails = { description = registry },
          }
        end
      end
    end
  end

  _cache[path] = items
  return items
end

-- Check whether the cursor is currently inside a string literal using TreeSitter.
local function in_string_node()
  local ok, node = pcall(vim.treesitter.get_node)
  if not ok or not node then return true end -- allow if TS unavailable
  local t = node:type()
  -- TypeScript string node types
  return t == "string_fragment"
      or t == "template_chars"
      or t == "jsx_text"
      or t:find("string") ~= nil
end

function source.new()
  return setmetatable({}, { __index = source })
end

function source:enabled()
  local ft = vim.bo.filetype
  if ft ~= "typescript" and ft ~= "javascript" then return false end
  return vim.fn.filereadable(registry_path()) == 1
end

function source:get_completions(_, callback)
  if not in_string_node() then
    callback({ is_incomplete_forward = false, is_incomplete_backward = false, items = {} })
    return
  end

  -- Parse lazily; result is cached for the session.
  local items = parse(registry_path())
  callback({
    is_incomplete_forward = false,
    is_incomplete_backward = false,
    items = items,
  })
end

-- Allow blink.cmp to call reload() if needed (e.g. after a new /probejs dump).
function source:reload()
  _cache = {}
end

return source
