-- lua/minecraft_registry_source.lua
-- Custom blink.cmp completion source for ProbeJS-generated Minecraft registry IDs.
-- Provides fuzzy-filtered completions (e.g. 'minecraft:diamond_sword') inside
-- string literals in TypeScript/JavaScript files, reading from
-- .vscode/probe.code-snippets generated by /probejs dump in-game.

local source = {}

-- Per-path cache so reopening Neovim in a different project re-parses.
local _cache = {} -- [path] -> blink CompletionItem[]

local function snippets_path()
  return vim.fn.getcwd() .. "/.vscode/probe.code-snippets"
end

-- Parse probe.code-snippets and build a flat list of CompletionItems.
-- Each registry entry body is: "${1|id1,id2,...|}"
-- We extract every id and label it with its registry name.
local function parse(path)
  if _cache[path] then return _cache[path] end

  local f = io.open(path, "r")
  if not f then return {} end
  local raw = f:read("*a")
  f:close()

  local ok, data = pcall(vim.json.decode, raw)
  if not ok or type(data) ~= "table" then return {} end

  local Value = require("blink.cmp.types").CompletionItemKind.Value
  local Plain = vim.lsp.protocol.InsertTextFormat.PlainText

  local items = {}
  local seen = {} -- deduplicate: keep first occurrence per unique id

  for _, snippet in pairs(data) do
    local body = type(snippet.body) == "table" and snippet.body[1] or snippet.body
    if type(body) ~= "string" then goto continue end

    -- Locate the choices: "${1|...|}"
    local s = body:find("${1|", 1, true)
    local e = s and body:find("|}", s + 4, true)
    if not (s and e) then goto continue end

    local inner = body:sub(s + 4, e - 1)
    -- Registry name from description: 'All available items in the registry "name"'
    local registry = (snippet.description or ""):match('"([^"]+)"') or ""

    for id in inner:gmatch("[^,]+") do
      if not seen[id] then
        seen[id] = true
        items[#items + 1] = {
          label = id,
          kind = Value,
          insertText = id,
          insertTextFormat = Plain,
          labelDetails = { description = registry },
        }
      end
    end

    ::continue::
  end

  _cache[path] = items
  return items
end

-- Check whether the cursor is currently inside a string literal using TreeSitter.
local function in_string_node()
  local ok, node = pcall(vim.treesitter.get_node)
  if not ok or not node then return true end -- allow if TS unavailable
  local t = node:type()
  -- TypeScript string node types
  return t == "string_fragment"
      or t == "template_chars"
      or t == "jsx_text"
      or t:find("string") ~= nil
end

function source.new()
  return setmetatable({}, { __index = source })
end

function source:enabled()
  local ft = vim.bo.filetype
  if ft ~= "typescript" and ft ~= "javascript" then return false end
  return vim.fn.filereadable(snippets_path()) == 1
end

function source:get_completions(_, callback)
  if not in_string_node() then
    callback({ is_incomplete_forward = false, is_incomplete_backward = false, items = {} })
    return
  end

  -- Parse lazily; result is cached for the session.
  local items = parse(snippets_path())
  callback({
    is_incomplete_forward = false,
    is_incomplete_backward = false,
    items = items,
  })
end

-- Allow blink.cmp to call reload() if needed (e.g. after a new /probejs dump).
function source:reload()
  _cache = {}
end

return source
